### PR TITLE
Pull request for WAZO-2017-rename-wazo-stat

### PR DESCRIPTION
**Pull request by fblackburn1**

### CODE REVIEW

**Review by pc-m — COMMENTED** [review]
:+1:

**Review by pc-m — COMMENTED** [review]
The log file and config files have not been moved. I've seen that you added rename in the dependencies. Did you forget to include the postinst?

**Comment by pc-m** [comment]
> The log file and config files have not been moved. I've seen that you added rename in the dependencies. Did you forget to include the postinst?

Fixed, thanks!

**Comment by fblackburn1** [comment]
> The log file and config files have not been moved. I've seen that you added rename in the dependencies. Did you forget to include the postinst?

Oh well see :+1: thanks

**Pull request merged**
